"""Generate the offline Mock catalog from backend constants without importing app code.

Run: python scripts/sync-profile-tags.py [--check] [--backend-root PATH]
"""
import argparse
import ast
import json
from pathlib import Path


def main():
    frontend = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--backend-root", type=Path, default=frontend.parent / "xuanshiai" / "xuanshiai")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    tree = ast.parse((args.backend_root / "app/core/profile_tags.py").read_text(encoding="utf-8"))
    names = {"LEGACY_TAG_CATEGORIES", "TAG_CATEGORIES", "MAX_PERSONAL_TAGS", "MAX_CUSTOM_TAGS", "CUSTOM_TAG_MIN_LENGTH", "CUSTOM_TAG_MAX_LENGTH", "TAG_CATALOG_REVISION"}
    values = {}
    for node in tree.body:
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and node.target.id in names:
            # Trusted constant expressions may reference an earlier catalog tuple.
            values[node.target.id] = eval(compile(ast.Expression(node.value), str(args.backend_root), "eval"), {"__builtins__": {}}, values)
    categories = [{"key": key, "label": label, "options": list(options)}
                  for key, label, options in values["TAG_CATEGORIES"]]
    tags = [tag for category in categories for tag in category["options"]]
    if len(tags) != len({tag.strip().casefold() for tag in tags}):
        raise SystemExit("Duplicate or ambiguous canonical tags in backend catalog")
    catalog = {"version": "personal-v2", "catalog_revision": values["TAG_CATALOG_REVISION"],
               "max_tags": values["MAX_PERSONAL_TAGS"], "recommended_min": 3,
               "custom": {"enabled": True, "max_tags": values["MAX_CUSTOM_TAGS"],
                          "min_length": values["CUSTOM_TAG_MIN_LENGTH"], "max_length": values["CUSTOM_TAG_MAX_LENGTH"]},
               "categories": categories}
    content = ("// Generated by scripts/sync-profile-tags.py; edit app/core/profile_tags.py in the backend.\n"
               "export const mockProfileTagOptions = " + json.dumps(catalog, ensure_ascii=False, indent=2) + "\n")
    target = frontend / "mock/profile-tags.uts"
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            raise SystemExit("Mock catalog differs from backend. Run python scripts/sync-profile-tags.py")
        print(f"Catalog parity OK: {len(categories)} categories, {len(tags)} tags")
    else:
        target.write_text(content, encoding="utf-8")
        print(f"Generated {target}: {len(tags)} tags")


if __name__ == "__main__":
    main()
